### ISSUE TITLE
Build Errors under Cordova-Android 7.0.0

### ISSUE THREAD

**Issue by tzeroem** [icsfl/cordova-honeywell#7]
I have some build errors after upgrading to cordova-android 7.0.0.
Under Cordova-Android 6.4.0 everything works fine.
What have I done:
`cordova create myapp`
`cordova platform add android@7.0.0`
`cordova plugin add https://github.com/nosTa1337/cordova-honeywell.git`

and then i got:

D:\Coding\Nodejs\Cordova\myapp>cordova build
cp: copyFileSync: could not write to dest file (code=ENOENT):D:\Coding\Nodejs\Cordova\myapp\platforms\android\res\xml\co
nfig.xml

(node:12856) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. (Parsing D:\Coding\Nodejs\Cordova\myapp\platforms\android\res\xml\config.xml failed)
    at EventEmitter.emit (events.js:186:19) at EventEmitter.module.exports.emit (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17) at EventEmitter.module.exports.emit (D:\Coding\Nodejs\Cordova\myapp\platforms\android\cordova\node_modules\cordova-common\src\events.js:68:30)at new ConfigParser (D:\Coding\Nodejs\Cordova\myapp\platforms\android\cordova\node_modules\cordova-common\src\Config
Parser\ConfigParser.js:34:16) at updateConfigFilesFrom (D:\Coding\Nodejs\Cordova\myapp\platforms\android\cordova\lib\prepare.js:106:18) at Api.module.exports.prepare (D:\Coding\Nodejs\Cordova\myapp\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (D:\Coding\Nodejs\Cordova\myapp\platforms\android\cordova\Api.js:192:45)
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:106:36 at _fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)at self.promiseDispatch.done (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\n
ode_modules\q\q.js:816:30)
(node:12856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

**Comment by andreujuanc** [comment]
Hi, IDK if it's the same issue as i had, but i think it's worth trying.

Add this pluggin with this config:
```
<plugin name="cordova-android-support-gradle-release" spec="^1.4.3">
        <variable name="ANDROID_SUPPORT_VERSION" value="24.+" />
 </plugin>
```
You can experiment with the value, which is the minimum version to support.



Problem with cordova is that every plugin has it own requirements and sometimes the are conflics.

If this does not solve your problem, please reply back.

Cheers
